/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ziliriproject;

/**
 *
 * @author Tuti
 */
public class opsice extends javax.swing.JFrame {

    /**
     * Creates new form opsice
     */
    public opsice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hampersce = new javax.swing.JButton();
        buketce = new javax.swing.JButton();
        balik1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 79, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(958, 770));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/bouquetopsi.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/hampersopsi.jpg"))); // NOI18N

        hampersce.setBackground(new java.awt.Color(255, 204, 255));
        hampersce.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        hampersce.setForeground(new java.awt.Color(196, 79, 130));
        hampersce.setText("Hampers");
        hampersce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hampersce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hampersceActionPerformed(evt);
            }
        });

        buketce.setBackground(new java.awt.Color(255, 204, 255));
        buketce.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        buketce.setForeground(new java.awt.Color(196, 79, 130));
        buketce.setText("Bouquet");
        buketce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buketce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buketceActionPerformed(evt);
            }
        });

        balik1.setBackground(new java.awt.Color(255, 204, 255));
        balik1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        balik1.setForeground(new java.awt.Color(196, 79, 130));
        balik1.setText(" back");
        balik1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balik1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(buketce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hampersce)
                .addGap(155, 155, 155))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(balik1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buketce)
                    .addComponent(hampersce))
                .addGap(49, 49, 49)
                .addComponent(balik1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balik1ActionPerformed
        // TODO add your handling code here:
        pilihgender pg = new pilihgender();
            pg.setLocationRelativeTo(null);
            pg.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_balik1ActionPerformed

    private void buketceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buketceActionPerformed
        // TODO add your handling code here:
        opsibelice2 obce2 = new opsibelice2();
        obce2.setLocationRelativeTo(null);
        obce2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buketceActionPerformed

    private void hampersceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hampersceActionPerformed
        // TODO add your handling code here:
        opsibelice obce = new opsibelice();
        obce.setLocationRelativeTo(null);
        obce.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hampersceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opsice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opsice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opsice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opsice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                opsice oce = new opsice();
                oce.setLocationRelativeTo(null);
                oce.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balik1;
    private javax.swing.JButton buketce;
    private javax.swing.JButton hampersce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
