/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ziliriproject;

/**
 *
 * @author Tuti
 */
public class opsibelice extends javax.swing.JFrame {
    totalbelanja Totalbelanja;
    int count1ce = 0;
    int count2ce = 0;
    int count3ce = 0;
    int harga1ce;
    int harga2ce;
    int harga3ce;
    String nama1ce;
    String nama2ce;
    String nama3ce;

    /**
     * Creates new form opsibelice
     */
    public opsibelice() {
        initComponents();
        Totalbelanja = new totalbelanja();
    }
    public opsibelice (totalbelanja Totalbelanja) {
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        plus1 = new javax.swing.JButton();
        plus2 = new javax.swing.JButton();
        plus3 = new javax.swing.JButton();
        min3 = new javax.swing.JButton();
        min2 = new javax.swing.JButton();
        min1 = new javax.swing.JButton();
        hasil3 = new javax.swing.JLabel();
        hasil2 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JLabel();
        balik2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        keranjang1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        keranjang2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        keranjang3 = new javax.swing.JButton();
        kekeranjang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 79, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(958, 665));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/hampersce2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/hampersce1.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/hampersce3.jpg"))); // NOI18N
        jLabel5.setText("jLabel3");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        plus1.setBackground(new java.awt.Color(255, 204, 255));
        plus1.setForeground(new java.awt.Color(196, 79, 130));
        plus1.setText("+");
        plus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus1ActionPerformed(evt);
            }
        });

        plus2.setBackground(new java.awt.Color(255, 204, 255));
        plus2.setForeground(new java.awt.Color(196, 79, 130));
        plus2.setText("+");
        plus2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus2ActionPerformed(evt);
            }
        });

        plus3.setBackground(new java.awt.Color(255, 204, 255));
        plus3.setForeground(new java.awt.Color(196, 79, 130));
        plus3.setText("+");
        plus3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus3ActionPerformed(evt);
            }
        });

        min3.setBackground(new java.awt.Color(255, 204, 255));
        min3.setForeground(new java.awt.Color(196, 79, 130));
        min3.setText("-");
        min3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min3ActionPerformed(evt);
            }
        });

        min2.setBackground(new java.awt.Color(255, 204, 255));
        min2.setForeground(new java.awt.Color(196, 79, 130));
        min2.setText("-");
        min2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min2ActionPerformed(evt);
            }
        });

        min1.setBackground(new java.awt.Color(255, 204, 255));
        min1.setForeground(new java.awt.Color(196, 79, 130));
        min1.setText("-");
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min1ActionPerformed(evt);
            }
        });

        hasil3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil3.setText("0");

        hasil2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil2.setText("0");

        hasil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil1.setText("0");

        balik2.setBackground(new java.awt.Color(255, 204, 255));
        balik2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        balik2.setForeground(new java.awt.Color(196, 79, 130));
        balik2.setText(" back");
        balik2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balik2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("Paket 2 - 70k");

        keranjang1.setBackground(new java.awt.Color(255, 204, 255));
        keranjang1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        keranjang1.setForeground(new java.awt.Color(196, 79, 130));
        keranjang1.setText("Tambah ke keranjang");
        keranjang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjang1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("Paket 1 - 50k");

        keranjang2.setBackground(new java.awt.Color(255, 204, 255));
        keranjang2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        keranjang2.setForeground(new java.awt.Color(196, 79, 130));
        keranjang2.setText("Tambah ke keranjang");
        keranjang2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjang2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 204, 255));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 255));
        jLabel6.setText("Paket 3 - 100k");

        keranjang3.setBackground(new java.awt.Color(255, 204, 255));
        keranjang3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        keranjang3.setForeground(new java.awt.Color(196, 79, 130));
        keranjang3.setText("Tambah ke keranjang");
        keranjang3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjang3ActionPerformed(evt);
            }
        });

        kekeranjang.setBackground(new java.awt.Color(255, 204, 255));
        kekeranjang.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        kekeranjang.setForeground(new java.awt.Color(196, 79, 130));
        kekeranjang.setText("Lihat Keranjang");
        kekeranjang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kekeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kekeranjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 423, Short.MAX_VALUE)
                                .addComponent(kekeranjang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(balik2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(min3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(min1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plus3)
                                    .addComponent(hasil3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plus1)
                                    .addComponent(plus2)
                                    .addComponent(hasil2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(min2))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(keranjang1)
                                    .addComponent(keranjang2)
                                    .addComponent(jLabel6)
                                    .addComponent(keranjang3)))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plus1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasil1)
                            .addComponent(keranjang1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(min1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plus2)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keranjang2)
                            .addComponent(min2))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasil2))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(plus3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keranjang3)
                            .addComponent(hasil3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(min3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(balik2)
                                    .addComponent(kekeranjang))
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus1ActionPerformed
        // TODO add your handling code here:
        count1ce++;
        hasil1.setText(count1ce + "");
    }//GEN-LAST:event_plus1ActionPerformed

    private void plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus2ActionPerformed
        // TODO add your handling code here:
        count2ce++;
        hasil2.setText(count2ce + "");
    }//GEN-LAST:event_plus2ActionPerformed

    private void plus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus3ActionPerformed
        // TODO add your handling code here:
        count3ce++;
        hasil3.setText(count3ce + "");
    }//GEN-LAST:event_plus3ActionPerformed

    private void min3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min3ActionPerformed
        // TODO add your handling code here:
        count3ce--;
        hasil3.setText(count3ce + "");
    }//GEN-LAST:event_min3ActionPerformed

    private void min2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min2ActionPerformed
        // TODO add your handling code here:
        count2ce--;
        hasil2.setText(count2ce + "");
    }//GEN-LAST:event_min2ActionPerformed

    private void min1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min1ActionPerformed
        // TODO add your handling code here:
        count1ce--;
        hasil1.setText(count1ce + "");
    }//GEN-LAST:event_min1ActionPerformed

    private void balik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balik2ActionPerformed
        // TODO add your handling code here:
        opsice oce = new opsice();
        oce.setLocationRelativeTo(null);
        oce.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_balik2ActionPerformed

    private void keranjang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjang1ActionPerformed
        // TODO add your handling code here:
        nama1ce = "Hampers Paket 1 (wanita)";
        harga1ce = count1ce * 50000;
        if(count1ce != 0){
            Totalbelanja.nama.add(nama1ce);
            Totalbelanja.total.add(harga1ce);
        }
    }//GEN-LAST:event_keranjang1ActionPerformed

    private void keranjang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjang2ActionPerformed
        // TODO add your handling code here:
        nama2ce = "Hampers Paket 2 (wanita)";
        harga2ce = count2ce * 70000;
        if(count2ce != 0){
            Totalbelanja.nama.add(nama2ce);
            Totalbelanja.total.add(harga2ce);
        }
    }//GEN-LAST:event_keranjang2ActionPerformed

    private void keranjang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjang3ActionPerformed
        // TODO add your handling code here:
        nama3ce = "Hampers Paket 3 (wanita)";
        harga3ce = count3ce * 100000;
        if(count3ce != 0){
            Totalbelanja.nama.add(nama3ce);
            Totalbelanja.total.add(harga3ce);
        }
    }//GEN-LAST:event_keranjang3ActionPerformed

    private void kekeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kekeranjangActionPerformed
        // TODO add your handling code here:
        totalbelanja tb = new totalbelanja();
        tb.setLocationRelativeTo(null);
        tb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kekeranjangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opsibelice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opsibelice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opsibelice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opsibelice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                opsibelice obce = new opsibelice();
                obce.setLocationRelativeTo(null);
                obce.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balik2;
    private javax.swing.JLabel hasil1;
    private javax.swing.JLabel hasil2;
    private javax.swing.JLabel hasil3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kekeranjang;
    private javax.swing.JButton keranjang1;
    private javax.swing.JButton keranjang2;
    private javax.swing.JButton keranjang3;
    private javax.swing.JButton min1;
    private javax.swing.JButton min2;
    private javax.swing.JButton min3;
    private javax.swing.JButton plus1;
    private javax.swing.JButton plus2;
    private javax.swing.JButton plus3;
    // End of variables declaration//GEN-END:variables
}
