/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ziliriproject;

/**
 *
 * @author user
 */
public class opsibelico2 extends javax.swing.JFrame {
    totalbelanja Totalbelanja;
    int count4co = 0;
    int count5co = 0;
    int count6co = 0;
    int harga4co;
    int harga5co;
    int harga6co;
    String nama4co;
    String nama5co;
    String nama6co;

    /**
     * Creates new form opsibelico2
     */
    public opsibelico2() {
        initComponents();
        Totalbelanja = new totalbelanja();
    }
    public opsibelico2 (totalbelanja Totalbelanja) {
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        plus1 = new javax.swing.JButton();
        plus2 = new javax.swing.JButton();
        plus3 = new javax.swing.JButton();
        min2 = new javax.swing.JButton();
        min1 = new javax.swing.JButton();
        min3 = new javax.swing.JButton();
        hasil1 = new javax.swing.JLabel();
        hasil2 = new javax.swing.JLabel();
        hasil3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keranjang1 = new javax.swing.JButton();
        keranjang2 = new javax.swing.JButton();
        keranjang3 = new javax.swing.JButton();
        balik2co = new javax.swing.JButton();
        kekeranjang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(958, 770));
        jPanel1.setRequestFocusEnabled(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/bungaco.jpg"))); // NOI18N
        jLabel5.setText("jLabel3");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/snackco.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziliriproject/bonekaco.jpg"))); // NOI18N
        jLabel7.setText("jLabel3");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        plus1.setBackground(new java.awt.Color(0, 0, 153));
        plus1.setForeground(new java.awt.Color(153, 153, 255));
        plus1.setText("+");
        plus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus1ActionPerformed(evt);
            }
        });

        plus2.setBackground(new java.awt.Color(0, 0, 153));
        plus2.setForeground(new java.awt.Color(153, 153, 255));
        plus2.setText("+");
        plus2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus2ActionPerformed(evt);
            }
        });

        plus3.setBackground(new java.awt.Color(0, 0, 153));
        plus3.setForeground(new java.awt.Color(153, 153, 255));
        plus3.setText("+");
        plus3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus3ActionPerformed(evt);
            }
        });

        min2.setBackground(new java.awt.Color(0, 0, 153));
        min2.setForeground(new java.awt.Color(153, 153, 255));
        min2.setText("-");
        min2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min2ActionPerformed(evt);
            }
        });

        min1.setBackground(new java.awt.Color(0, 0, 153));
        min1.setForeground(new java.awt.Color(153, 153, 255));
        min1.setText("-");
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min1ActionPerformed(evt);
            }
        });

        min3.setBackground(new java.awt.Color(0, 0, 153));
        min3.setForeground(new java.awt.Color(153, 153, 255));
        min3.setText("-");
        min3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min3ActionPerformed(evt);
            }
        });

        hasil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil1.setText("0");

        hasil2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil2.setText("0");

        hasil3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil3.setText("0");

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Bouquet Snack - 50k");

        jLabel3.setBackground(new java.awt.Color(255, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Bouquet Bunga - 100k");

        jLabel4.setBackground(new java.awt.Color(255, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Bouquet Boneka - 70k");

        keranjang1.setBackground(new java.awt.Color(0, 0, 153));
        keranjang1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        keranjang1.setForeground(new java.awt.Color(153, 153, 255));
        keranjang1.setText("Tambah ke keranjang");
        keranjang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjang1ActionPerformed(evt);
            }
        });

        keranjang2.setBackground(new java.awt.Color(0, 0, 153));
        keranjang2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        keranjang2.setForeground(new java.awt.Color(153, 153, 255));
        keranjang2.setText("Tambah ke keranjang");
        keranjang2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjang2ActionPerformed(evt);
            }
        });

        keranjang3.setBackground(new java.awt.Color(0, 0, 153));
        keranjang3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        keranjang3.setForeground(new java.awt.Color(153, 153, 255));
        keranjang3.setText("Tambah ke keranjang");
        keranjang3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjang3ActionPerformed(evt);
            }
        });

        balik2co.setBackground(new java.awt.Color(0, 0, 153));
        balik2co.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        balik2co.setForeground(new java.awt.Color(153, 153, 255));
        balik2co.setText("back");
        balik2co.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balik2co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balik2coActionPerformed(evt);
            }
        });

        kekeranjang.setBackground(new java.awt.Color(0, 0, 153));
        kekeranjang.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        kekeranjang.setForeground(new java.awt.Color(153, 153, 255));
        kekeranjang.setText("Lihat Keranjang");
        kekeranjang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kekeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kekeranjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plus2)
                                    .addComponent(plus1)
                                    .addComponent(min2)
                                    .addComponent(min1))
                                .addComponent(hasil2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hasil3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plus3)
                                    .addComponent(min3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(keranjang1))
                                .addGap(424, 424, 424))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(keranjang2)
                                    .addComponent(jLabel3)
                                    .addComponent(keranjang3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kekeranjang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balik2co)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hasil1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plus1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(keranjang1)
                                .addGap(14, 14, 14)
                                .addComponent(min1)))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plus2)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasil2)
                            .addComponent(keranjang2))
                        .addGap(18, 18, 18)
                        .addComponent(min2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plus3)
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hasil3)
                                    .addComponent(keranjang3))
                                .addGap(18, 18, 18)
                                .addComponent(min3)
                                .addGap(25, 25, 25)))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balik2co)
                            .addComponent(kekeranjang))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus1ActionPerformed
        // TODO add your handling code here:
        count4co++;
        hasil1.setText(count4co + "");
    }//GEN-LAST:event_plus1ActionPerformed

    private void plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus2ActionPerformed
        // TODO add your handling code here:
        count5co++;
        hasil2.setText(count5co + "");
    }//GEN-LAST:event_plus2ActionPerformed

    private void plus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus3ActionPerformed
        // TODO add your handling code here:
        count6co++;
        hasil3.setText(count6co + "");
    }//GEN-LAST:event_plus3ActionPerformed

    private void min2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min2ActionPerformed
        // TODO add your handling code here:
        count5co--;
        hasil2.setText(count5co + "");
    }//GEN-LAST:event_min2ActionPerformed

    private void min1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min1ActionPerformed
        // TODO add your handling code here:
        count4co--;
        hasil1.setText(count4co + "");
    }//GEN-LAST:event_min1ActionPerformed

    private void min3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min3ActionPerformed
        // TODO add your handling code here:
        count6co--;
        hasil3.setText(count6co + "");
    }//GEN-LAST:event_min3ActionPerformed

    private void keranjang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjang1ActionPerformed
        // TODO add your handling code here:
        nama4co = "Bouquet Snack (pria)";
        harga4co = count4co * 50000;
        if(count4co != 0){
            Totalbelanja.nama.add(nama4co);
            Totalbelanja.total.add(harga4co);
        }
    }//GEN-LAST:event_keranjang1ActionPerformed

    private void keranjang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjang2ActionPerformed
        // TODO add your handling code here:
        nama5co = "Bouquet Boneka (pria)";
        harga5co = count5co * 70000;
        if(count5co != 0){
            Totalbelanja.nama.add(nama5co);
            Totalbelanja.total.add(harga5co);
        }
    }//GEN-LAST:event_keranjang2ActionPerformed

    private void keranjang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjang3ActionPerformed
        // TODO add your handling code here:
        nama6co = "Bouquet Bunga (pria)";
        harga6co = count6co * 100000;
        if(count6co != 0){
            Totalbelanja.nama.add(nama6co);
            Totalbelanja.total.add(harga6co);
        }
    }//GEN-LAST:event_keranjang3ActionPerformed

    private void balik2coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balik2coActionPerformed
        // TODO add your handling code here:
        opsico oco = new opsico();
        oco.setLocationRelativeTo(null);
        oco.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_balik2coActionPerformed

    private void kekeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kekeranjangActionPerformed
        // TODO add your handling code here:
        Totalbelanja.setLocationRelativeTo(null);
        Totalbelanja.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kekeranjangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opsibelico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opsibelico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opsibelico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opsibelico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                opsibelico2 obco2 = new opsibelico2();
                obco2.setLocationRelativeTo(null);
                obco2.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balik2co;
    private javax.swing.JLabel hasil1;
    private javax.swing.JLabel hasil2;
    private javax.swing.JLabel hasil3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kekeranjang;
    private javax.swing.JButton keranjang1;
    private javax.swing.JButton keranjang2;
    private javax.swing.JButton keranjang3;
    private javax.swing.JButton min1;
    private javax.swing.JButton min2;
    private javax.swing.JButton min3;
    private javax.swing.JButton plus1;
    private javax.swing.JButton plus2;
    private javax.swing.JButton plus3;
    // End of variables declaration//GEN-END:variables
}
